# Generated by Django 5.2 on 2025-06-07 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_computerspecification_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diskspecification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='diskspecification',
            name='computer_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disks_spec', to='inventory.computerspecification'),
        ),
        migrations.AddField(
            model_name='diskspecification',
            name='monoblok_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disks_spec', to='inventory.monoblokspecification'),
        ),
        migrations.AddField(
            model_name='diskspecification',
            name='notebook_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disks_spec', to='inventory.notebookspecification'),
        ),
    ]
