# Generated by Django 5.2 on 2025-06-07 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_diskspecification_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskspecification',
            name='computer_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disk_specifications', to='inventory.computerspecification'),
        ),
        migrations.AlterField(
            model_name='diskspecification',
            name='monoblok_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disk_specifications', to='inventory.monoblokspecification'),
        ),
        migrations.AlterField(
            model_name='diskspecification',
            name='notebook_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disk_specifications', to='inventory.notebookspecification'),
        ),
    ]
