# Generated by Django 5.2 on 2025-04-29 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер договора')),
                ('file', models.FileField(upload_to='contracts/', verbose_name='Файл договора')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договора',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа оборудования')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название оборудования')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipment_photos/', verbose_name='Фото оборудования')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.contractdocument', verbose_name='Договор')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='university.room', verbose_name='Кабинет')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='inventory.equipmenttype', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='ComputerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(help_text='Процессор', max_length=255, verbose_name='Процессор')),
                ('ram', models.CharField(help_text='Оперативная память', max_length=255, verbose_name='Оперативная память')),
                ('storage', models.CharField(help_text='Накопитель (SSD/HDD)', max_length=255, verbose_name='Накопитель')),
                ('has_keyboard', models.BooleanField(default=True, help_text='Есть ли клавиатура')),
                ('has_mouse', models.BooleanField(default=True, help_text='Есть ли мышь')),
                ('monitor_size', models.CharField(blank=True, help_text='Размер монитора (если есть)', max_length=50, verbose_name='Размер монитора')),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='computer_details', to='inventory.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Компьютерные характеристики',
                'verbose_name_plural': 'Компьютерные характеристики',
            },
        ),
        migrations.CreateModel(
            name='MovementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата перемещения')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.equipment', verbose_name='Оборудование')),
                ('from_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_out', to='university.room', verbose_name='Из кабинета')),
                ('to_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_in', to='university.room', verbose_name='В кабинет')),
            ],
            options={
                'verbose_name': 'История перемещений',
                'verbose_name_plural': 'История перемещений',
            },
        ),
    ]
