# Generated by Django 5.2 on 2025-06-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_gpu_gpuspecification_computerspecification_gpus_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computerspecification",
            name="gpus",
        ),
        migrations.RemoveField(
            model_name="monoblokspecification",
            name="gpus",
        ),
        migrations.RemoveField(
            model_name="notebookspecification",
            name="gpus",
        ),
    ]
