# Generated by Django 5.2 on 2025-06-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_remove_computerspecification_gpus_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gpu",
            name="memory_gb",
        ),
        migrations.RemoveField(
            model_name="gpu",
            name="memory_type",
        ),
        migrations.RemoveField(
            model_name="gpuspecification",
            name="memory_gb",
        ),
        migrations.RemoveField(
            model_name="gpuspecification",
            name="memory_type",
        ),
    ]
