# Generated by Django 5.2 on 2025-06-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_remove_gpu_memory_gb_remove_gpu_memory_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disk",
            name="disk_type",
            field=models.CharField(
                choices=[
                    ("HDD", "HDD"),
                    ("NVMEM2SSD", "NVMe M2 SSD"),
                    ("SATASSD", "SATA SSD"),
                ],
                max_length=10,
                verbose_name="Тип диска",
            ),
        ),
        migrations.AlterField(
            model_name="diskspecification",
            name="disk_type",
            field=models.CharField(
                choices=[
                    ("HDD", "HDD"),
                    ("NVMEM2SSD", "NVMe M2 SSD"),
                    ("SATASSD", "SATA SSD"),
                ],
                max_length=10,
                verbose_name="Тип диска",
            ),
        ),
    ]
