# Generated by Django 5.2 on 2025-06-11 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_alter_disk_disk_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="computerdetails",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_computer_details_author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="computerdetails",
            name="specification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_computer_details",
                to="inventory.computerspecification",
                verbose_name="Исходная спецификация",
            ),
        ),
        migrations.AddField(
            model_name="monoblokchar",
            name="specification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_monoblok_details",
                to="inventory.monoblokspecification",
                verbose_name="Исходная спецификация",
            ),
        ),
        migrations.AddField(
            model_name="notebookchar",
            name="specification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_notebook_details",
                to="inventory.notebookspecification",
                verbose_name="Исходная спецификация",
            ),
        ),
    ]
