# Generated by Django 5.2 on 2025-06-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0017_computerdetails_author_computerdetails_specification_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contractdocument",
            name="valid_until",
        ),
        migrations.AlterField(
            model_name="equipment",
            name="inn",
            field=models.CharField(verbose_name="ИНН"),
        ),
    ]
