# Generated by Django 5.2 on 2025-06-12 10:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_remove_contractdocument_valid_until_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extenderchar",
            name="specification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_extender_details",
                to="inventory.extenderspecification",
                verbose_name="Исходная спецификация",
            ),
        ),
        migrations.AddField(
            model_name="monoblokchar",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Создано",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monoblokchar",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AddField(
            model_name="notebookchar",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AddField(
            model_name="printerchar",
            name="specification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_printer_details",
                to="inventory.printerspecification",
                verbose_name="Исходная спецификация",
            ),
        ),
        migrations.AddField(
            model_name="projectorchar",
            name="specification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_projector_details",
                to="inventory.projectorspecification",
                verbose_name="Исходная спецификация",
            ),
        ),
        migrations.AddField(
            model_name="routerchar",
            name="specification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_router_details",
                to="inventory.routerspecification",
                verbose_name="Исходная спецификация",
            ),
        ),
        migrations.AddField(
            model_name="tvchar",
            name="specification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tv_details",
                to="inventory.tvspecification",
                verbose_name="Исходная спецификация",
            ),
        ),
        migrations.AddField(
            model_name="whiteboardchar",
            name="specification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_whiteboard_details",
                to="inventory.whiteboardspecification",
                verbose_name="Исходная спецификация",
            ),
        ),
        migrations.AlterField(
            model_name="monoblokchar",
            name="has_keyboard",
            field=models.BooleanField(
                default=True,
                help_text="Есть ли клавиатура",
                verbose_name="Есть клавиатура",
            ),
        ),
        migrations.AlterField(
            model_name="monoblokchar",
            name="has_mouse",
            field=models.BooleanField(
                default=True, help_text="Есть ли мышь", verbose_name="Есть мышь"
            ),
        ),
        migrations.AlterField(
            model_name="notebookchar",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="projectorchar",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="projectorchar",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="whiteboardchar",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="whiteboardchar",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
    ]
