# Generated by Django 5.2 on 2025-06-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0021_computerdetails_title_computerspecification_title_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contractdocument",
            name="signed_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата заключения"
            ),
        ),
    ]
