# Generated by Django 5.2 on 2025-06-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0023_inntemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="photo",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Фото оборудования"
            ),
        ),
    ]
