# Generated by Django 5.2 on 2025-04-26 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название университета')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название корпуса')),
                ('address', models.TextField(blank=True, verbose_name='Адрес корпуса')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='building_photos/', verbose_name='Фото корпуса')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='university.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
            },
        ),
    ]
