# Generated by Django 5.2 on 2025-04-26 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название факультета')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='faculty_photos/', verbose_name='Фото факультета')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='university.building', verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
                'unique_together': {('building', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название кафедры')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='university.faculty', verbose_name='Факультет')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер кабинета')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название (если есть)')),
                ('is_special', models.BooleanField(default=False, verbose_name='Специальный кабинет')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='room_photos/', verbose_name='Фото кабинета')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='university.floor', verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
                'unique_together': {('floor', 'number')},
            },
        ),
    ]
