# Generated by Django 5.2 on 2025-04-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_faculty_department_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Кафедра', 'verbose_name_plural': 'Кафедры'},
        ),
        migrations.AddField(
            model_name='room',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='room_qrcodes/', verbose_name='QR-код кабинета'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('faculty', 'name')},
        ),
    ]
