# Generated by Django 5.2 on 2025-06-17 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0003_room_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_warehouse",
            field=models.BooleanField(default=False, verbose_name="Склад"),
        ),
        migrations.AlterField(
            model_name="room",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="university.building",
                verbose_name="Корпус",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="floor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="university.floor",
                verbose_name="Этаж",
            ),
        ),
    ]
